# Generated by Django 6.0.7 on 2026-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="campaigns",
            field=models.ManyToManyField(
                related_name="members",
                through="campaigns.CampaignMembership",
                to="campaigns.campaign",
            ),
        ),
    ]
