# Generated by Django 6.0.7 on 2026-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_campaigns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(max_length=100),
        ),
    ]
